baseURL: https://aaltomcc.github.io/cs-ej4101-fall-2019-012-advanced/
languageCode: en-us
title: Super Coffee Site
theme: cupper-hugo-theme

params:
  description: Below you can read more thoughts had during a cup of good coffee.
  footer: Made with [Hugo](https://gohugo.io/). Themed by a load of coffee.

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
